### ISSUE TITLE
Publish on bower

### ISSUE THREAD

**Issue by paladox** [PolymerElements/paper-ripple#103]
### Description
Please could you publish this on bower please?

### Steps to reproduce

1. going to bower and typing in paper-ripple brings up a separate repo compared to this one.

**Comment by notwaldorf** [comment]
That is pretty much the reason we don't publish on bower. Bower doesn't have namespaces, and since the `paper-*` names are usually already taken, we can't publish them. Since we can't publish _all_ of them, it's a safer bet to not try to publish any of them. 

All of the elements are searchable on webcomponents.org though!
