### ISSUE TITLE
noink property missing reflectToAttribute

### ISSUE THREAD

**Issue by CelineBen** [PolymerElements/paper-ripple#50]
Would it make sense to add `reflectToAttribute: true` to the noink property ? 
It looks like this is never applied:
```js
:host([noink]) {
    pointer-events: none;
}
```
Edit: I mean when the `paper-ripple` is added dynamically through another component such as `paper-button`.

**Comment by notwaldorf** [comment]
I've just landed a PR that makes `paper-ripple` have pointer-events none
all the time, so that style doesn't really make a difference anymore. Also,
there have been recent changes in `paper-ripple` and `paper-behaviors` that
make `noink` actually work correctly everywhere, so that style can just be
removed

**Comment by CelineBen** [comment]
Thank you.
