### ISSUE TITLE
setting 'display: none' on paper-ripples will cause a significant slow down 

### ISSUE THREAD

**Issue by fiws** [PolymerElements/paper-ripple#72]
I noticed this because I "disabled" paper-ripples on mobile using 'display: none' - sadly the performance got really bad by doing that.

demo: https://jsbin.com/samumobafi/edit?html,css,output

**Comment by notwaldorf** [comment]
That's probably because all the ripples are started, but since they're not growing, they can't be finished.

I think you should the `noink` attribute instead to disable the ripples: https://jsbin.com/ruwiwe/edit?html,css,output.

Please let us know if this doesn't work for you, and we'll re-open the issue.
